[package]
name = "rolodex"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
directories = "6.0.0"
ratatui = "0.29.0"
rusqlite = "0.36.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.23"
